// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from 'vue'
import { defineSliceZoneComponents } from '@prismicio/vue'

export const components = defineSliceZoneComponents({
  banner_copy: defineAsyncComponent(() => import('./BannerCopy/index.vue')),
  banner_image: defineAsyncComponent(() => import('./BannerImage/index.vue')),
  banner_video: defineAsyncComponent(() => import('./BannerVideo/index.vue')),
})
