<script setup>
const topicInput = ref('')
const result = ref('')
const submitting = ref(false)

const messages = ref([ { role: 'system', content: 'You are a helpful and humorous assistant designed to help visitors to the website of Tom Corbett learn more about him and his work.' } ])

async function onSubmit() {
  if (submitting.value) {return}
  submitting.value = true

  const newMessages = [
    ...messages.value,
    {
      role: 'user',
      content: specify(topicInput.value)
    }
  ]

  try {
    const response = await fetch('/api/generate', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ messages: newMessages }),
    })

    const data = await response.json()

    if (response.status !== 200) {
      throw data.error || new Error(`Request failed with status ${response.status}`)
    }

    result.value = data.result
    document.getElementById('topic').value = ''

    messages.value = [
      ...newMessages,
      data.result
    ]
  } catch(error) {
    // Consider implementing your own error handling logic here
    console.error(error)
    result.value = error.message
  } finally {
    submitting.value = false
  }
}

function setTopicInput(e) {
  topicInput.value = e.target.value
}

function specify(message) {
  return message.replaceAll('Tom', 'Tom Corbett').replaceAll(' he ', ' Tom Corbett ')
}

onMounted(() => {
  document.getElementById('topic').focus()
})

</script>

<template>
  <div class="chat-gptom">
    <div class="content">
      <h1>Ask GPTom about me!</h1>
      <div class="chat-result">
        <div
          v-if="submitting"
          class="loading"
        />
        <div :class="['result', submitting ? 'result-pend' : 'result-loaded']">
          <div
            v-for="message, idx in messages"
            :key="idx"
            :class="[ 'message', message.role ]"
          >
            {{ message.content }}
          </div>
        </div>
      </div>
      <div class="chat-input">
        <form @submit.prevent="onSubmit">
          <label
            class="chat-input-label"
            for="topic"
          >Ask whatever</label>
          <input
            id="topic"
            class="chat-input-field"
            type="text"
            name="topic"
            placeholder="Type…"
            value="What does Tom know about…"
            @change="setTopicInput"
          >
          <button
            class="chat-input-btn"
            type="submit"
            title="Find out"
          >
            ?
          </button>
        </form>
      </div>
      <div class="credit">
        <svg-open-ai />
        Responses generated by <a
          href="https://openai.com/"
          target="_blank"
          rel="noopener"
        >Open AI</a> API using a <a
          href="https://platform.openai.com/docs/guides/fine-tuning"
          target="_blank"
          rel="noopener"
        >fine-tuned</a> model
      </div>
    </div>
  </div>
</template>

<style lang="stylus">

@import "../../stylus/_variables"

.chat-gptom {
  h1 {
    fs(mp(0))
    color $dgry
    font-weight 600
    mgn(2, 0, 1)
  }

  .credit {
    color $blk
    fs(mp(-4))
    pad(1, 0)

    a {
      border-bottom 1px solid
    }

    svg {
      display inline-block
      fill $blk
      height 1rem
      width 1rem
      vertical-align middle
      margin-right 1em
    }

    +below($mobile) {
      display block
      white-space wrap
    }
  }
}

.chat-input {
  // font-family $lato
  fs(mp(1))
  font-weight 400
  mgn(1, 0)
  text-align right

  &-label,
  &-field,
  &-btn {
    color inherit
    font inherit
  }

  &-label {
    display block
    color $prpl
    fs(mp(-2))
    letter-spacing .1em
    text-transform uppercase
  }

  &-field {
    background none
    border 0
    outline 0
    pad(0, .5)
    mgn(0, .5, 0, 0)
    margin-left auto
    // background darken($blk, 50%)
    // border-radius 8px
    transition background-color 200ms
    transition-property background-color, border-color
    text-align right
    // width 34rem

    &:hover,
    &:focus-visible {
      // border-color darken($prpl, 60%)
      // background-color $blk
      color $w
    }
  }

  &-btn {
    background darken($prpl, 70%)
    border-radius 8px
    cursor pointer
    font-weight 900
    pad(0, 1)
    transition background-color 200ms

    &:hover,
    &:focus-visible {
      background-color darken($prpl, 65%)
    }
  }
}

.chat-result {
  // min-height 45vh
  pad(1, 0)
  position relative

  .loading {
    border 5px solid $prpl
    border-color $prpl transparent transparent transparent
    border-radius 1.2rem
    height 1.2rem
    position absolute
    top 0
    right 0
    width 1.2rem
    animation spin 2s $easeInOutCubic infinite
    pointer-events none
  }

  .result {
    position relative
    opacity 1
    transition opacity 200ms

    &-pend {
      opacity .7
    }
  }
}

.system {
  display none
}

.user {
  text-align right
}

@keyframes spin {
  0% {
    transform rotateZ(0deg)
  }
  100% {
    transform rotateZ(360deg)
  }
}

</style>
